name: bio-blocks
channels:
  - defaults
dependencies:
  - python=3.10
  - flask
  - ca-certificates
  - certifi
  - openssl
  - requests
  - numpy
  - pandas
  - matplotlib
  - scikit-image
  - torchvision
  - scikit-learn
  - nomkl
  - pillow